// <auto-generated />
namespace JobFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Solved : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Solved));
        
        string IMigrationMetadata.Id
        {
            get { return "202508042233196_Solved"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
