// <auto-generated />
namespace JobFinder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class New : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(New));
        
        string IMigrationMetadata.Id
        {
            get { return "202508011435008_New"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
